"""
Django settings for main project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from typing import List

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(BASE_DIR / '.env')
# load the hostname.txt file
with open(BASE_DIR / 'hostname.txt', 'r') as f:
    TOR_HIDDEN_SERVICE_HOSTNAME = f.read().strip()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-mdx0x2nl0qj%wtq(cvf@#1n*gd!9lcd0-phz!^55g(ljql9def'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Allow localhost and Tor hidden service .onion address
# Get .onion address from: sudo cat /var/lib/tor/django_hidden_service/hostname
ALLOWED_HOSTS: List[str] = [
    'localhost',
    '127.0.0.1',
    TOR_HIDDEN_SERVICE_HOSTNAME,
]



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'blog',
]

# Custom User Model
AUTH_USER_MODEL = 'blog.PublicKeyUser'


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'main.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'main.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Custom Authentication Backend
AUTHENTICATION_BACKENDS = [
    'blog.auth_backend.PublicKeyAuthBackend',
    'django.contrib.auth.backends.ModelBackend',  # Keep for admin
]

# Login URL - redirect to login page for key-based authentication
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'

# Password validation (not used for public key auth, but kept for admin)
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Session Security Settings
# Note: SESSION_COOKIE_SECURE is False because Tor hidden services use HTTP (not HTTPS)
# However, Tor provides encryption at the network layer, so this is acceptable
SESSION_COOKIE_HTTPONLY = True  # Prevents JavaScript access to session cookie
SESSION_COOKIE_SAMESITE = 'Lax'  # CSRF protection
SESSION_COOKIE_AGE = 60 * 60 * 24 * 7  # 7 days (matches user cleanup of 60 days)
SESSION_SAVE_EVERY_REQUEST = False  # Only save session when modified
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # Persist across browser restarts

# CSRF Security Settings
CSRF_COOKIE_HTTPONLY = True  # Prevents JavaScript access to CSRF token cookie
CSRF_COOKIE_SAMESITE = 'Lax'  # CSRF protection
# CSRF_COOKIE_SECURE is False for Tor hidden service (HTTP only)
