# Generated by Django 6.0.1 on 2026-01-11 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='signature',
            field=models.TextField(blank=True, help_text='Cryptographic signature of the post content'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='signature_valid',
            field=models.BooleanField(default=False, help_text='Whether the signature has been verified'),
        ),
    ]
