# Generated by Django 6.0.1 on 2026-01-11 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_signature_blogpost_signature_valid'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='blogpost',
            new_name='blog_blogpo_created_2e77d7_idx',
            old_name='trivia_blog_created_3f07ed_idx',
        ),
        migrations.RenameIndex(
            model_name='blogpost',
            new_name='blog_blogpo_slug_361555_idx',
            old_name='trivia_blog_slug_d4d20c_idx',
        ),
        migrations.RenameIndex(
            model_name='publickeyuser',
            new_name='blog_public_fingerp_29a3b8_idx',
            old_name='trivia_publ_fingerp_8cc4a3_idx',
        ),
        migrations.RenameIndex(
            model_name='publickeyuser',
            new_name='blog_public_last_lo_044d2d_idx',
            old_name='trivia_publ_last_lo_21bb21_idx',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.category'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='blog.tag'),
        ),
    ]
