import Footer from '@/components/header-footer/Footer';
import './globals.css';
import Header from '@/components/header-footer/Header';

export const metadata = {
  title: 'DKK Next Template',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}